documentation:
- changed-files:
  - any-glob-to-any-file: docs/**

terraform:
- changed-files:
  - any-glob-to-any-file: terraform/**

github_actions:
- changed-files:
  - any-glob-to-any-file: .github/workflows/**

docker:
- changed-files:
  - any-glob-to-any-file:
    - '**/Dockerfile'
    - '**/docker-compose*'

python:
- changed-files:
  - any-glob-to-any-file:
    - '**/*.py'
    - '**/requirements*.txt'

php:
- changed-files:
  - any-glob-to-any-file: '**/*.php'

go:
- changed-files:
  - any-glob-to-any-file: '**/*.go'

javascript:
- changed-files:
  - any-glob-to-any-file: '**/*.js'

dependencies:
- changed-files:
  - any-glob-to-any-file:
    - '**/requirements*.txt'
    - '**/package*.json'
    - '**/yarn*.lock'
    - '**/Gemfile*'
    - '**/composer*.json'
    - '**/go.mod'
    - '**/go.sum'
    - '**/vendor/**'
    - '**/node_modules/**'
    - '**/vendor/**'