services:
  mock-sirius:
    image: outofcoffee/imposter:4.9.2@sha256:a5c3f32236b7de8b9e1395657badcba39a85f52677cfaade78b7687590ef70fe
    healthcheck:
      test: [ "CMD", "imposter", "list", "-x" ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    volumes:
      - ./mock_sirius_backend:/opt/imposter/config

  localstack:
    image: localstack/localstack:4.14@sha256:3ebc37595918b8accb852f8048fef2aff047d465167edd655528065b07bc364a
    volumes:
      - "./localstack/init:/etc/localstack/init/ready.d"
    environment:
      AWS_DEFAULT_REGION: eu-west-1
    restart: unless-stopped

  redis:
    image: "redis:alpine@sha256:c5e375abb885e6b2021c0377879e4890bf76f9065b8922ffc113f2b226b9fc17"
    ports:
      - "0.0.0.0:6379:6379"

  api_gateway:
    build:
      context: ./lambda_functions/v1
    depends_on:
      - localstack
      - mock-sirius
      - redis
    volumes:
      - ./lambda_functions/v1/:/var/www/lambda_functions/v1/
    environment:
      ENVIRONMENT: local
      AWS_ACCESS_KEY_ID: testing
      AWS_SECRET_ACCESS_KEY: testing
      AWS_SECURITY_TOKEN: testing
      AWS_SESSION_TOKEN: testing
      AWS_DEFAULT_REGION: eu-west-1
      SIRIUS_BASE_URL: http://mock-sirius:8080
      SIRIUS_API_VERSION: v1
      SESSION_DATA: publicapi@opgtest.com
      LOCALSTACK_HOST: localstack
      REQUEST_CACHING: enabled
      REQUEST_CACHING_TTL: 48
      REQUEST_CACHING_NAME: opg-data-lpa
      REDIS_URL: redis://redis:6379
    networks:
      default:
        aliases:
          - lpa.local

  unit-test-lpa-data:
    image: unit-tests-request-handler:latest
    build:
      context: lambda_functions/v1
      dockerfile: Dockerfile-tests
    volumes:
      - "./pact:/tmp/pact"
      - /var/run/docker.sock:/var/run/docker.sock

  lpa-data:
    image: lpa-data-lambda:latest
    build:
      dockerfile: lambda_functions/v1/Dockerfile-Function
