---
swagger: '2.0'
info:
  version: 1.0.0
  title: Sirius Public API
  description: |
    Fixed and versioned Sirius API endpoints allowing applications to integrate with Sirius in a contractually guaranteed way.

    Once these endpoints are fixed at a major version, they may not change. A breaking change requires a new major version while maintaining the functionality of the existing versions.

    Versions may only be decomissioned following discussion and agreement with clients.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
basePath: /api
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /health-check:
    get:
      summary: Sirius healthcheck
      x-swagger-router-controller: app
      operationId: healthcheck
      responses:
        '200':
          description: Record found and retrieved

        '400':
          description: Invalid query
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
definitions:
  Error:
    type: object
    required:
      - validation_errors
      - status
      - detail
    properties:
      validation_errors:
        type: object
        description: All validation errors are returned in this property. There is a child property named after the request property that faled validation e.g. appointmentType which itself has a property for each type of failed validation with a description
      type:
        type: string
        description: a URL to a document describing the error condition (optional, and "about:blank" is assumed if none is provided; should resolve to a human-readable document; Apigility always provides this)
        example: http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html
      title:
        type: string
        description: a brief title for the error condition (required; and should be the same for every problem of the same type; Apigility always provides this)
        example: Bad Request
      status:
        type: string
        description: the HTTP status code for the current request (optional; Apigility always provides this)
        example: '400'
      detail:
        type: string
        description: error details specific to this request (optional; Apigility requires it for each problem)
        example: Payload failed validation
      instance:
        type: string
        description: URI identifying the specific instance of this problem (optional; Apigility currently does not provide this)
