FROM public.ecr.aws/lambda/python:3.13@sha256:42fd4356bf50655e7fff84abd2b7da8ac83536e363bb15c360a07f1781198e15 AS build

WORKDIR /app

COPY lambda_functions/v1/requirements/requirements.txt requirements.txt

RUN pip install -r requirements.txt -t python/

COPY lambda_functions/v1/functions/lpa/ python/

FROM public.ecr.aws/lambda/python:3.31@sha256:f3ed51a5bddffbc2b73480c0829f1eb0e7dc0c3ddc6bead52ac1a0fbd14ce14f AS runtime

WORKDIR /var/task

COPY --from=build /app/python ./

RUN rm -f /usr/local/bin/aws-lambda-rie

CMD [ "app.lpa.lambda_handler" ]