FROM public.ecr.aws/lambda/python:3.13@sha256:f769f1f81b8ee38c2e09130a7f2e3c2a3643eba3e48ec15a6f93fb6f44947254

COPY /functions/lpa/ ${LAMBDA_TASK_ROOT}/lambda_functions/v1/functions/lpa
COPY /tests/  ${LAMBDA_TASK_ROOT}/lambda_functions/v1/tests
COPY requirements/requirements.txt requirements.txt
COPY requirements/dev-requirements.txt dev-requirements.txt

RUN python -m pip install --upgrade pip && \
        python -m pip install \
        --target ${LAMBDA_TASK_ROOT} \
        --requirement requirements.txt \
        --requirement dev-requirements.txt && \
        python -m pip install coverage==7.5.0

RUN echo "2023.7.20250512" > /etc/dnf/vars/releasever && \
        dnf clean all && \
        dnf -y update sqlite-libs libxml2 && \
        dnf clean all


ENV PYTHONPATH "${PYTHONPATH}:${LAMBDA_TASK_ROOT}"

COPY --chmod=755 run-tests.sh run-tests.sh

ENTRYPOINT [ "./run-tests.sh" ]
