FROM public.ecr.aws/lambda/python:3.13.2025.09.07.12@sha256:92367e96b60cbb24efaefe04f7c94302d5cb272ae0ff6b2becf545f650dd0541 AS build

WORKDIR /app

COPY lambda_functions/v1/requirements/requirements.txt requirements.txt

RUN pip install -r requirements.txt -t python/

COPY lambda_functions/v1/functions/lpa/ python/

RUN echo "2023.7.20250512" > /etc/dnf/vars/releasever && \
    dnf clean all && \
    dnf -y update sqlite-libs libxml2 && \
    dnf clean all

FROM public.ecr.aws/lambda/python:3.13.2025.09.07.12@sha256:92367e96b60cbb24efaefe04f7c94302d5cb272ae0ff6b2becf545f650dd0541 AS runtime

WORKDIR /var/task

COPY --from=build /app/python ./

RUN rm -f /usr/local/bin/aws-lambda-rie

CMD [ "app.lpa.lambda_handler" ]