FROM public.ecr.aws/lambda/python:3.13@sha256:94fba3db411aa55b762db473af64c49b8551ef6fbe9c95c913aef5aa44c278da

COPY /functions/lpa/ ${LAMBDA_TASK_ROOT}/lambda_functions/v1/functions/lpa
COPY /tests/  ${LAMBDA_TASK_ROOT}/lambda_functions/v1/tests
COPY requirements/requirements.txt requirements.txt
COPY requirements/dev-requirements.txt dev-requirements.txt

RUN python -m pip install --upgrade pip && \
        python -m pip install \
        --target ${LAMBDA_TASK_ROOT} \
        --requirement requirements.txt \
        --requirement dev-requirements.txt && \
        python -m pip install coverage==7.5.0

RUN echo "2023.7.20250512" > /etc/dnf/vars/releasever && \
        dnf clean all && \
        dnf -y update sqlite-libs libxml2 && \
        dnf clean all
        

ENV PYTHONPATH "${PYTHONPATH}:${LAMBDA_TASK_ROOT}"

COPY --chmod=755 run-tests.sh run-tests.sh

ENTRYPOINT [ "./run-tests.sh" ]
