FROM public.ecr.aws/lambda/python:3.13@sha256:c6a7c7b1af774c2f7832c4d27c35acf554e46013d3dcf15e8c4e7a4b493afeee AS build

WORKDIR /app

COPY lambda_functions/v1/requirements/requirements.txt requirements.txt

RUN pip install -r requirements.txt -t python/

COPY lambda_functions/v1/functions/lpa/ python/

FROM public.ecr.aws/lambda/python:3.13@sha256:c6a7c7b1af774c2f7832c4d27c35acf554e46013d3dcf15e8c4e7a4b493afeee AS runtime

WORKDIR /var/task

COPY --from=build /app/python ./

RUN rm -f /usr/local/bin/aws-lambda-rie

CMD [ "app.lpa.lambda_handler" ]
