---
version: '3'

services:
  postgres:
    image: postgres
    ports:
      - "8765:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    networks:
      - default
  broker_app:
    image: pactfoundation/pact-broker
    ports:
      - "9897:80"
      - "9292:9292"
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres
    networks:
      default:
        aliases:
          - local.broker
  python_tests:
      build:
          context: .
      depends_on:
          - broker_app
      environment:
          PYTHONPATH: /
          CI: "true"
      restart: always
      networks:
        - default
  provider_mock:
      build:
          context: ./mock
      depends_on:
          - postgres
      ports:
        - "5000:5000"
      environment:
          PYTHONPATH: /
      restart: always
      networks:
        default:
          aliases:
            - local.mock
