name: "[Job] Destroy Environment"

on:
  workflow_call:
    inputs:
      workspace_name:
        description: "The terraform workspace to target for environment actions"
        required: true
        type: string
    secrets:
      allowlist_deploy_key:
        description: "SSH Deploy Key"
        required: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Error if protected
        if: ${{ contains(fromJSON('["development", "preproduction", "production", "demo", "integration"]'), inputs.workspace_name) }}
        run: |
          echo "Cannot destroy protected Environment"
          exit 1

  terraform_environment_workflow:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: check
    env:
      tf_dir: "./terraform/environment"
      TF_VAR_default_role: ${{ vars.DEVELOPMENT_ROLE }}
      TF_VAR_management_role: ${{ vars.MANAGEMENT_ROLE }}
      TF_VAR_lambda_image_tag: "latest"
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: "0"
      - name: "Parse terraform version [directory: ${{ env.tf_dir }}]"
        id: tf_version
        uses: ministryofjustice/opg-github-actions/actions/terraform-version@ae37b9b322286123971417e82b665e56e9d6aa3f # v4.10.3
        with:
          terraform_directory: ${{ env.tf_dir }}
      - name: "Terraform version [${{ steps.tf_version.outputs.version }}]"
        run: echo "terraform version [${{ steps.tf_version.outputs.version }}]" >> $GITHUB_STEP_SUMMARY
        working-directory: ${{ env.tf_dir }}
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ steps.tf_version.outputs.version }}
          terraform_wrapper: false
      - name: Configure AWS Credentials For Terraform
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
          role-duration-seconds: 3600
          role-session-name: oidc-opg-data-lpa-destory-environment-github-action
      - uses: ministryofjustice/opg-github-actions/actions/github-deploy-key@ae37b9b322286123971417e82b665e56e9d6aa3f # v4.10.3
        with:
          deploy_key: ${{ secrets.allowlist_deploy_key }}

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ${{ env.tf_dir }}

      - name: Terraform Destroy
        env:
          WORKSPACE_NAME: ${{ inputs.workspace_name }}
        run: |
          terraform workspace select $WORKSPACE_NAME
          terraform destroy -auto-approve
          terraform workspace select default
          terraform workspace delete $WORKSPACE_NAME
        working-directory: ${{ env.tf_dir }}
