permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  id-token: write
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: write
  statuses: none

on:
  workflow_call:
    inputs:
      branch_name:
        description: Branch name
        type: string
        required: false
      semver_tag:
        description: Semver tag
        required: true
        type: string
    secrets:
      SNYK_OPG_ORG_TOKEN:
        required: true
    outputs:
      ecr_image_uri:
        value: '${{ jobs.docker_build_scan_push.outputs.ecr_image_uri }}'
        description: ECR image URI

jobs:
  docker_build_scan_push:
    name: 'Build, Scan and Push Lambdas'
    runs-on: ubuntu-latest
    outputs:
      ecr_image_uri: ${{ steps.docker_tags.outputs.semver_tag }}
    strategy:
      matrix:
        data:
          - name: lpa-data-lambda
            docker_build_directory: lambda_functions/v1
            snyk_policy_path: lambda_functions/v1/.snyk
            ecr_repository: integrations
            dockerfile: Function
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ vars.OIDC_MANAGEMENT_ECR_ROLE }}
          role-duration-seconds: 3600
          role-session-name: OPGLPADataGithubActionECRPush

      - name: ECR Login
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          registries: 311462405659

      - name: Generate tags for Docker
        env:
          SEMVER_TAG: '${{ inputs.semver_tag }}'
          ECR_REGISTRY: '${{ steps.login_ecr.outputs.registry }}'
          ECR_REPOSITORY: '${{ matrix.data.ecr_repository }}/${{ matrix.data.name }}'
        id: docker_tags
        run: >
          if ${{ inputs.branch_name == 'main' }}; then
            echo "tags=$ECR_REGISTRY/$ECR_REPOSITORY:latest,$ECR_REGISTRY/$ECR_REPOSITORY:main-$SEMVER_TAG" >> $GITHUB_OUTPUT
            echo "semver_tag=$ECR_REGISTRY/$ECR_REPOSITORY:main-$SEMVER_TAG" >> $GITHUB_OUTPUT
          else
            echo "tags=$ECR_REGISTRY/$ECR_REPOSITORY:$SEMVER_TAG" >> $GITHUB_OUTPUT
            echo "semver_tag=$ECR_REGISTRY/$ECR_REPOSITORY:$SEMVER_TAG" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          platforms: 'linux/amd64'
          file: >-
            ${{ matrix.data.docker_build_directory }}/Dockerfile-${{
            matrix.data.dockerfile }}
          push: true
          load: true
          tags: '${{ steps.docker_tags.outputs.tags }}'
          provenance: false

      - name: Snyk Scan
        uses: ministryofjustice/opg-github-actions/actions/snyk-scan@8dea82fc8b8e7ffca431f0fb83848d523147ccd8 #v4.5.0
        with:
          SNYK_TEST_IMAGE: ${{ steps.docker_tags.outputs.semver_tag }}
          SNYK_TOKEN: ${{ secrets.SNYK_OPG_ORG_TOKEN }}
          snyk_policy_path: ./${{ matrix.data.snyk_policy_path }}
      
      - name: Upload Snyk scan results
        uses: github/codeql-action/upload-sarif@0d579ffd059c29b07949a3cce3983f0780820c98 #v4.32.6
        if: always()
        with:
          sarif_file: test-results/snyk.sarif
