permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: write
  statuses: none

on:
  workflow_call:
    inputs:
      data_lpa_api_url:
        description: 'The url of the data lpa api gateway'
        required: true
        type: string
      working_directory:
        description: 'Working Directory to run tests from'
        required: true
        type: string
      tests_directory:
        description: 'Directory containing Pytest tests'
        required: true
        type: string
      specific_tests:
        description: 'File path to specific Pytest tests - currently used to run 1 test as a smoke test'
        required: false
        type: string
        default: ""
    secrets:
      AWS_ACCESS_KEY_ID_ACTIONS:
        description: 'AWS Access Key ID'
        required: false
      AWS_SECRET_ACCESS_KEY_ACTIONS:
        description: 'AWS Secret Access Key'
        required: false

jobs:
  integration_tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Configure AWS Credentials For integration tests
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        if: ${{ env.AWS_ACCESS_KEY_ID != '' && env.AWS_SECRET_ACCESS_KEY != '' }}
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          role-duration-seconds: 900
          role-session-name: GitHubActionsIntegrationTests

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.13"

      - name: Install integration test requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ inputs.tests_directory }}/requirements.txt

      - name: Run tests with Pytest
        env:
          DATA_LPA_API_URL: ${{ inputs.data_lpa_api_url }}
          SPECIFIC_TESTS: ${{ inputs.specific_tests}}
        working-directory: ${{ inputs.working_directory }}
        run: |
          coverage run -m pytest $SPECIFIC_TESTS -v -s

      - name: Generate Coverage Report
        working-directory: ${{ inputs.working_directory }}
        run: |
          coverage report -m
