permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: write
  statuses: none

on:
  workflow_call:
    inputs:
      environment_name:
        description: 'The name of the environment'
        required: true
        type: string
      working_directory:
        description: 'Working Directory to run tests from'
        required: true
        type: string
      tests_directory:
        description: 'Directory containing Pytest tests'
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID_ACTIONS:
        description: 'AWS Access Key ID'
        required: false
      AWS_SECRET_ACCESS_KEY_ACTIONS:
        description: 'AWS Secret Access Key'
        required: false

jobs:
  integration_tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials For integration tests
        uses: aws-actions/configure-aws-credentials@v4
        if: ${{ env.AWS_ACCESS_KEY_ID != '' && env.AWS_SECRET_ACCESS_KEY != '' }}
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          role-duration-seconds: 900
          role-session-name: GitHubActionsIntegrationTests

      - name: Setup Python
        uses: actions/setup-python@9a7ac94420f42ee15fc60ab88d0dca4be1fd5757
        with:
          python-version: "3.12"

      - name: Install integration test requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ inputs.tests_directory }}/requirements.txt

      - name: Run tests with Pytest
        env:
          ENVIRONMENT_NAME: ${{ inputs.environment_name }}
        working-directory: ${{ inputs.working_directory }}
        run: |
          coverage run -m pytest  -v -s

      - name: Generate Coverage Report
        working-directory: ${{ inputs.working_directory }}
        run: |
          coverage report -m
