name: "[Analysis] TFSec"

on:
  push:
    branches: [ main ]
    paths:
      - "**.tf"
  schedule:
    # 7am every wednesday
    - cron: '0 7 * * 3'

permissions:
  security-events: write
  actions: read
  checks: read
  contents: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:
  tfsec:
    name: TFSec Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Run tfsec
        uses: tfsec/tfsec-sarif-action@21ded20e8ca120cd9d3d6ab04ef746477542a608 # v0.1.4
        with:
          sarif_file: tfsec.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@f1f6e5f6af878fb37288ce1c627459e94dbf7d01 # v3.30.1
        with:
          sarif_file: tfsec.sarif
