name: "[Analysis] TFSec"

on:
  push:
    branches: [ main ]
    paths:
      - "**.tf"
  schedule:
    # 7am every wednesday
    - cron: '0 7 * * 3'

permissions:
  security-events: write
  actions: read
  checks: read
  contents: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

jobs:
  tfsec:
    name: TFSec Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run tfsec
        uses: tfsec/tfsec-sarif-action@21ded20e8ca120cd9d3d6ab04ef746477542a608 # v0.1.4
        with:
          sarif_file: tfsec.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@fc7e4a0fa01c3cca5fd6a1fddec5c0740c977aa2 # v3.28.14
        with:
          sarif_file: tfsec.sarif
