permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: write
  statuses: none

on:
  workflow_call:
    inputs:
      branch_name:
        description: 'Branch Name'
        required: true
        type: string
    secrets:
      aws_access_key_id:
        description: 'AWS Access Key ID'
        required: true
      aws_secret_access_key:
        description: 'AWS Secret Access Key'

jobs:
  integration_tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        id: checkout_code
        uses: actions/checkout@v4.1.1

      - name: Configure AWS Credentials For integration tests
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: eu-west-1
          role-duration-seconds: 900
          role-session-name: GitHubActionsIntegrationTests

      - name: Setup Python
        uses: actions/setup-python@9a7ac94420f42ee15fc60ab88d0dca4be1fd5757
        with:
          python-version: '3.10'

      - name: Install requirements
        id: requirements
        run: |
          pip install -r ./integration_tests/v1/requirements.txt

      - name: Run Integration Tests
        env:
          BRANCH_NAME: ${{ inputs.branch_name }}
        id: integration_tests
        working-directory: ./integration_tests
        run: |
          echo "my branch name is" ; echo $BRANCH_NAME
          python -m pytest -n2 --dist=loadfile --html=report.html --self-contained-html
