name: "[Workflow] Path to Live"

concurrency:
  group: ${{ github.workflow }}

on:
  push:
    branches:
      - main

defaults:
 run:
  shell: bash

jobs:
  set_variables:
    name: output workflow variables
    runs-on: ubuntu-latest
    outputs:
      environment_terraform_version: ${{ steps.terraform_version_environment.outputs.version }}
      semver_tag: ${{ steps.semver_tag.outputs.created_tag }}
    steps:
      - name: Set terraform version - environment
        id: terraform_version_environment
        uses: ministryofjustice/opg-github-actions/.github/actions/terraform-version@v2.7.3
        with:
          terraform_directory: "./terraform/environment"
      - name: "Semver tag"
        id: semver_tag
        uses: ministryofjustice/opg-github-actions/.github/actions/semver-tag@v2.3.1
        with:
          prerelease: true
          with_v: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

  docker_build_scan_push:
    name: Build, Scan and Push
    needs:
      - set_variables
    uses: ./.github/workflows/_docker_build_scan_push.yml
    with:
      build_latest: true
      semver_tag: ${{ needs.set_variables.outputs.semver_tag }}
    secrets: inherit # pragma: allowlist secret

  terraform_preprod_environment_apply:
    name: Terraform - Preproduction - Environment - Apply
    needs:
      - set_variables
      - docker_build_scan_push
    uses: ministryofjustice/opg-github-workflows/.github/workflows/build-infrastructure-terraform.yml@v3.1.0
    with:
      terraform_version: ${{ needs.set_variables.outputs.environment_terraform_version }}
      terraform_directory: "./terraform/environment"
      terraform_workspace: preproduction
      is_ephemeral: false
      terraform_apply: true
      terraform_variables: "-var=lambda_image_uri=${{ needs.docker_build_scan_push.outputs.ecr_image_uri }}"
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID_ACTIONS: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      AWS_SECRET_ACCESS_KEY_ACTIONS: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
      PAGERDUTY_TOKEN: ""

  terraform_prod_environment_apply:
    name: Terraform - Production - Environment - Apply
    needs:
      - set_variables
      - docker_build_scan_push
      - terraform_preprod_environment_apply
    uses: ministryofjustice/opg-github-workflows/.github/workflows/build-infrastructure-terraform.yml@v3.1.0
    with:
      terraform_version: ${{ needs.set_variables.outputs.environment_terraform_version }}
      terraform_directory: "./terraform/environment"
      terraform_workspace: production
      is_ephemeral: false
      terraform_apply: true
      terraform_variables: "-var=lambda_image_uri=${{ needs.docker_build_scan_push.outputs.ecr_image_uri }}"
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID_ACTIONS: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      AWS_SECRET_ACCESS_KEY_ACTIONS: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
      PAGERDUTY_TOKEN: ""