name: "[Workflow] Path to Live"

concurrency:
  group: ${{ github.workflow }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
 run:
  shell: bash

jobs:
  branch_name:
    name: "Generate a safe branch name"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/data-parse-branch-name.yml@6e25a7da7d1f1d728915ef6a51f1a269e9751069 # v3.18.0

  set_variables:
    name: output workflow variables
    runs-on: ubuntu-latest
    outputs:
      semver_tag: ${{ steps.semver_tag.outputs.tag }}
      commit_sha: ${{ steps.commit_sha.outputs.sha }}
    steps:
      - name: checkout the project
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: "0"
      - name: Set terraform version - environment
        id: terraform_version_environment
        uses: ministryofjustice/opg-github-actions/actions/terraform-version@4f345be3f706950d1fdc05bc86383967a149bd99 # v4.3.4
        with:
          terraform_directory: "./terraform/environment"
      - name: "Semver tag"
        id: semver_tag
        uses: ministryofjustice/opg-github-actions/actions/semver@4f345be3f706950d1fdc05bc86383967a149bd99 # v4.3.4
        with:
          prerelease: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit
        id: commit_sha
        run: echo "sha=${{ github.sha }}" >> "$GITHUB_OUTPUT"

  terraform_lint:
    name: Lint & Validate Terraform
    uses: ./.github/workflows/_terraform_lint.yml
    with:
      oidc_role: ${{ vars.OIDC_MAIN_ROLE }}
    secrets:
      allowlist_deploy_key: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}
      github_access_token: ${{ secrets.GITHUB_TOKEN }}

  python_unit_tests:
    name: Python Unit Tests
    needs:
      - branch_name
      - set_variables
    uses: ./.github/workflows/_python_unit_tests.yml
    with:
      branch_name: ${{ needs.branch_name.outputs.branch_name }}
      commit_sha: ${{ needs.set_variables.outputs.commit_sha }}
      semver_tag: ${{ needs.set_variables.outputs.semver_tag }}
    secrets:
      pact_broker_password: ${{ secrets.PACT_BROKER_PASSWORD }}

  docker_build_scan_push:
    name: Build, Scan and Push
    needs:
      - branch_name
      - python_unit_tests
      - set_variables
    uses: ./.github/workflows/_docker_build_scan_push.yml
    with:
      branch_name: ${{ needs.branch_name.outputs.safe }}
      semver_tag: ${{ needs.set_variables.outputs.semver_tag }}
    secrets: inherit # pragma: allowlist secret

  terraform_development_environment_apply:
    name: "Terraform Apply Development"
    needs:
      [
        branch_name,
        docker_build_scan_push,
        set_variables,
        terraform_lint
      ]
    uses: ./.github/workflows/_terraform.yml
    with:
      apply: true
      workspace_name: development
      oidc_role: ${{ vars.OIDC_MAIN_ROLE }}
      default_role: ${{ vars.DEVELOPMENT_ROLE }}
      management_role: ${{ vars.MANAGEMENT_ROLE }}
      version_tag: ${{ needs.docker_build_scan_push.outputs.ecr_image_uri }}
    secrets:
      allowlist_deploy_key: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}
      github_access_token: ${{ secrets.GITHUB_TOKEN }}

  integration_test_development:
    name: Run Integration Tests on Ephemeral Environment
    needs: terraform_development_environment_apply
    uses: ./.github/workflows/_integration_tests.yml
    with:
      data_lpa_api_url: "https://dev.lpa.api.opg.service.justice.gov.uk/v1"
      oidc_role: ${{ vars.OIDC_DEVELOPMENT_TEST_RUNNER_ROLE }}
      working_directory: "./integration_tests"
      tests_directory: "./integration_tests/v1"

  terraform_preprod_environment_apply:
    name: "Terraform Apply Preproduction"
    needs:
      - docker_build_scan_push
      - integration_test_development
    uses: ./.github/workflows/_terraform.yml
    with:
      apply: true
      workspace_name: preproduction
      oidc_role: ${{ vars.OIDC_MAIN_ROLE }}
      default_role: ${{ vars.PREPRODUCTION_MAIN_ROLE }}
      management_role: ${{ vars.MANAGEMENT_ROLE }}
      version_tag: ${{ needs.docker_build_scan_push.outputs.ecr_image_uri }}
    secrets:
      allowlist_deploy_key: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}
      github_access_token: ${{ secrets.GITHUB_TOKEN }}

  smoke_test_preprod:
    name: Smoke Test Preproduction
    needs: terraform_preprod_environment_apply
    uses: ./.github/workflows/_integration_tests.yml
    with:
      data_lpa_api_url: "https://pre.lpa.api.opg.service.justice.gov.uk/v1"
      oidc_role: ${{ vars.OIDC_PREPRODUCTION_TEST_RUNNER_ROLE }}
      working_directory: "./integration_tests"
      tests_directory: "./integration_tests/v1"
      specific_tests: "./v1/test_healthcheck.py"

  terraform_prod_environment_apply:
    name: "Terraform Apply Production"
    needs:
      - docker_build_scan_push
      - smoke_test_preprod
    uses: ./.github/workflows/_terraform.yml
    with:
      apply: true
      workspace_name: production
      oidc_role: ${{ vars.OIDC_MAIN_ROLE }}
      default_role: ${{ vars.PRODUCTION_MAIN_ROLE }}
      management_role: ${{ vars.MANAGEMENT_ROLE }}
      version_tag: ${{ needs.docker_build_scan_push.outputs.ecr_image_uri }}
    secrets:
      allowlist_deploy_key: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}
      github_access_token: ${{ secrets.GITHUB_TOKEN }}

  terraform_integration_environment_apply:
    name: "Terraform Apply Integration"
    needs:
        - docker_build_scan_push
        - terraform_prod_environment_apply
    uses: ./.github/workflows/_terraform.yml
    with:
      apply: true
      workspace_name: integration
      oidc_role: ${{ vars.OIDC_MAIN_ROLE }}
      default_role: ${{ vars.DEVELOPMENT_ROLE }}
      management_role: ${{ vars.MANAGEMENT_ROLE }}
      version_tag: ${{ needs.docker_build_scan_push.outputs.ecr_image_uri }}
    secrets:
      allowlist_deploy_key: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}
      github_access_token: ${{ secrets.GITHUB_TOKEN }}

  terraform_demo_environment_apply:
    name: "Terraform Apply Demo"
    needs:
        - docker_build_scan_push
        - terraform_prod_environment_apply
    uses: ./.github/workflows/_terraform.yml
    with:
      apply: true
      workspace_name: demo
      oidc_role: ${{ vars.OIDC_MAIN_ROLE }}
      default_role: ${{ vars.DEVELOPMENT_ROLE }}
      management_role: ${{ vars.MANAGEMENT_ROLE }}
      version_tag: ${{ needs.docker_build_scan_push.outputs.ecr_image_uri }}
    secrets:
      allowlist_deploy_key: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
