name: PR Closed Workflow

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  branch_name:
    name: "Generate a safe branch name"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/data-parse-branch-name.yml@17ca444d0b23a0f9f6c612f1bfb8dc9be358f235 # v3.19.6

  destroy-pr-env:
    name: Destroy PR Environment
    needs: [branch_name]
    uses: ./.github/workflows/_destroy_environment.yml
    with:
      workspace_name: ${{ github.event.pull_request.number }}${{ needs.branch_name.outputs.safe }}
    secrets:
      allowlist_deploy_key: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}