name: "[Workflow] Pull Request Path"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  checks: read
  contents: write
  deployments: none
  id-token: write
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: none

defaults:
 run:
  shell: bash

jobs:
  pr_label:
    runs-on: ubuntu-latest
    name: Label PR
    steps:
      - uses: actions/labeler@main
        with:
          configuration-path: ".github/labeller.yml"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true

  branch_name:
    name: "Generate a safe branch name"
    uses:  ministryofjustice/opg-github-workflows/.github/workflows/data-parse-branch-name.yml@361d19a6d7b291dab5d46f04765239341a4ca86b # v3.16.0

  set_variables:
    name: output workflow variables
    runs-on: ubuntu-latest
    outputs:
      environment_terraform_version: ${{ steps.terraform_version_environment.outputs.version }}
      semver_tag: ${{ steps.semver_tag.outputs.tag }}
      commit_sha: ${{ steps.commit_sha.outputs.sha }}
    steps:
      - name: checkout the project
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: "0"
      - name: "Semver tag"
        id: semver_tag
        uses: ministryofjustice/opg-github-actions/actions/semver@4f345be3f706950d1fdc05bc86383967a149bd99 # v4.3.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Commit"
        id: commit_sha
        run: |
          if [ "${{ github.head_ref }}" == "" ]; then
              echo "sha=${{github.sha}}" >> $GITHUB_OUTPUT
          else
              echo "sha=${{github.event.pull_request.head.sha}}" >> $GITHUB_OUTPUT
          fi

  python_unit_tests:
    name: Python Unit Tests
    needs:
      - branch_name
      - set_variables
    uses: ./.github/workflows/_python_unit_tests.yml
    with:
      branch_name: ${{ needs.branch_name.outputs.branch_name }}
      commit_sha: ${{ needs.set_variables.outputs.commit_sha }}
      semver_tag: ${{ needs.set_variables.outputs.semver_tag }}
    secrets:
      pact_broker_password: ${{ secrets.PACT_BROKER_PASSWORD }}

  docker_build_scan_push:
    name: Build, Scan and Push
    needs:
      - set_variables
      - python_unit_tests
    uses: ./.github/workflows/_docker_build_scan_push.yml
    with:
      semver_tag: ${{ needs.set_variables.outputs.semver_tag }}
    secrets: inherit # pragma: allowlist secret

  plan-environment:
    strategy:
      matrix:
        include:
          - workspace_name: development
            oidc_role: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
            default_role: ${{ vars.DEVELOPMENT_ROLE }}
            management_role: ${{ vars.MANAGEMENT_ROLE }}
          - workspace_name: preproduction
            oidc_role: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
            default_role: ${{ vars.PREPRODUCTION_PULL_REQUEST_ROLE }}
            management_role: ${{ vars.MANAGEMENT_ROLE }}
          - workspace_name: production
            oidc_role: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
            default_role: ${{ vars.PRODUCTION_PULL_REQUEST_ROLE }}
            management_role: ${{ vars.MANAGEMENT_ROLE }}
    name: "TF Plan Environment: ${{ matrix.workspace_name }}"
    needs: 
      [
        set_variables,
        docker_build_scan_push,
        branch_name,
      ]
    uses: ./.github/workflows/_terraform.yml
    with:
      apply: false
      workspace_name: ${{ matrix.workspace_name }}
      oidc_role: ${{ matrix.oidc_role }}
      default_role: ${{ matrix.default_role }}
      management_role: ${{ matrix.management_role }}
      version_tag: ${{ needs.docker_build_scan_push.outputs.ecr_image_uri }}
    secrets:
      allowlist_deploy_key: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY }}
      github_access_token: ${{ secrets.GITHUB_TOKEN }}

  ephemeral_environment:
    name: Create Ephemeral Environment
    needs:
      [
        set_variables,
        docker_build_scan_push,
        branch_name,
      ]
    uses: ./.github/workflows/_terraform.yml
    with:
      workspace_name: ${{ github.event.pull_request.number }}${{ needs.branch_name.outputs.safe }}
      oidc_role: ${{ vars.OIDC_PULL_REQUEST_ROLE }}
      default_role: ${{ vars.DEVELOPMENT_ROLE }}
      management_role: ${{ vars.MANAGEMENT_ROLE }}
      version_tag: ${{ needs.docker_build_scan_push.outputs.ecr_image_uri }}
      apply: true
    secrets:
      allowlist_deploy_key: ${{ secrets.SSH_PRIVATE_KEY_ALLOW_LIST_REPOSITORY}}
      github_access_token: ${{ secrets.GITHUB_TOKEN }}

  integration_tests:
    name: Run Integration Tests on Ephemeral Environment
    needs:
      - ephemeral_environment
    uses: ./.github/workflows/_integration_tests.yml
    with:
      data_lpa_api_url: "https://${{ needs.ephemeral_environment.outputs.base_url }}/v1"
      working_directory: "./integration_tests"
      tests_directory: "./integration_tests/v1"
